
services:
  flowops:
    build:
      context: .
      dockerfile: FlowOps/Dockerfile
    image: flowops:dev
    container_name: flowops
    ports:
      - "5056:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"

      FLOWOPS_ROLE: "api"

      ConnectionStrings__FlowOpsDatabase: "${FlowOpsDatabase}"

      RabbitMQ__HostName: "${RabbitMQ__HostName}"
      RabbitMQ__Port: "${RabbitMQ__Port}"
      RabbitMQ__UserName: "${RabbitMQ__UserName}"
      RabbitMQ__Password: "${RabbitMQ__Password}"
      RabbitMQ__VirtualHost: "${RabbitMQ__VirtualHost}"
      Logging__LogLevel__Microsoft.EntityFrameworkCore.Database.Command: None
  billing:
     image: "flowops:dev"
     container_name: flowops-billing
     ports:
      - "5057:8080"
     environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"

      FLOWOPS_ROLE: "billing"

      ConnectionStrings__FlowOpsDatabase: "${FlowOpsDatabase}"

      RabbitMQ__HostName: "${RabbitMQ__HostName}"
      RabbitMQ__Port: "${RabbitMQ__Port}"
      RabbitMQ__UserName: "${RabbitMQ__UserName}"
      RabbitMQ__Password: "${RabbitMQ__Password}"
      RabbitMQ__VirtualHost: "${RabbitMQ__VirtualHost}"

  reporting:
     image: "flowops:dev"
     container_name: flowops-reporting
     ports:
      - "5058:8080"
     environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"

      FLOWOPS_ROLE: "reporting"

      ConnectionStrings__FlowOpsDatabase: "${FlowOpsDatabase}"


      RabbitMQ__HostName: "${RabbitMQ__HostName}"
      RabbitMQ__Port: "${RabbitMQ__Port}"
      RabbitMQ__UserName: "${RabbitMQ__UserName}"
      RabbitMQ__Password: "${RabbitMQ__Password}"
      RabbitMQ__VirtualHost: "${RabbitMQ__VirtualHost}"